name: 编译 Electron 应用

on:
  push:
    branches: [ test ]
  workflow_dispatch:

jobs:
  build:
    name: Build for ${{ matrix.identifier }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            identifier: win-x64
            ext: .exe
          - os: macos-latest
            identifier: mac-arm64
            ext: ''
          - os: ubuntu-latest
            identifier: linux-x64
            ext: ''
    steps:
      - name: 拉取分支
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: 设置环境变量
        run: |
            echo "HASH=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV

      - name: 设置 Nodejs
        uses: actions/setup-node@v4
        with:
            node-version: 20.x

      - name: 更新依赖
        run: yarn

      - name: 安装 bsdtar(Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y bsdtar

      - name: 将 qqface 的软链接改成真实路径(win)
        if: matrix.os == 'windows-latest'
        run: |
            Remove-Item src/renderer/public/img/qqface
            Copy-Item src/renderer/src/assets/img/qq-face/public/assets/qq_emoji/resfile/emoji src/renderer/public/img/qqface -Recurse

      - name: 构建 stapxs-qq-lite-x
        run: yarn build:electron

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
            name: stapxs-qq-lite-x-${{ matrix.os }}
            path: dist_electron
